### ISSUE TITLE
Change background color of notebooks

### ISSUE THREAD

**Issue by inf17101** [opensearch-project/dashboards-notebooks#103]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to change the background color in notebooks. It always uses the background color and design from the selected theme mode (dark mode or white).

**Describe the solution you'd like**
It would be very nice to have a button to change the background color of the notebook, maybe with custom color codes.

**Comment by joshuali925** [comment]
Thanks for filling an issue, notebooks is merged into [Observability](https://github.com/opensearch-project/observability) plugin as it is, and we have added dark mode support in this PR https://github.com/opensearch-project/observability/pull/206

Let me know or open a new issue in Observability repo if opensearch 1.2 still doesn't work for you
