### ISSUE TITLE
[BUG] "Learn more" Documentation Link Incorrect

### ISSUE THREAD

**Issue by ahopp** [opensearch-project/dashboards-notebooks#27]
**Describe the bug**
"Learn more" within Notebooks links to https://opendistro.github.io/for-elasticsearch-docs/docs/kibana/notebooks/ rather than https://docs-beta.opensearch.org/docs/opensearch-dashboards/notebooks/.

**To Reproduce**
1. Go to 'Notebooks'
2. Click on 'Learn more'

**Expected behavior**
Link should pass to https://docs-beta.opensearch.org/docs/opensearch-dashboards/notebooks/

**Plugins**
N/A

**Screenshots**
![Learn more](https://user-images.githubusercontent.com/9532728/119105314-0ac6bf00-b9d2-11eb-925c-b0689ff0b4f1.png)

**Host/Environment (please complete the following information):**
N/A

**Additional context**
None

**Comment by joshuali925** [comment]
this should be fixed previously, closing this, thanks
