### ISSUE TITLE
[BUG] Long passages of text trigger unusual error message

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/dashboards-notebooks#32]
**Describe the bug**
Paragraph codeblocks fail with very long text entry (tired pasting in the entire text of Moby Dick, several Mbs) -> Error message "Error running paragraph, please make sure you have the correct permission." 

**Expected behavior**
Either the error message would be more exact (it has nothing to do with permissions) or limit the number of character allowed in the text box

**Plugins**
All OpenSearch

**Host/Environment (please complete the following information):**
 - OS: macOS 
 - Version: Chrome / Version 90.0.4430.212 (Official Build) (x86_64)
 - OpenSearch 1.0 RC1

**Comment by joshuali925** [comment]
Thanks for reporting this, the dashboards server has a max_payload limit, and rejects if a request is too large. Will work on a fix

**Comment by joshuali925** [comment]
closed by #40
