### ISSUE TITLE
[BUG] "Search notebooks" only searches the *names* of notebooks.

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/dashboards-notebooks#33]
**Describe the bug**
On the notebooks dashboard (`/app/notebooks-dashboards`) the search bar only searches the names the notebooks, not any contents. This is confusing.

**Expected behavior**
If you have the word "peanut" on one of your reports, querying the bar on `/app/notebooks-dashboards` for "peanut" would filter the list to only reports that contain "peanut"

**Plugins**
All OpenSearch

**Host/Environment (please complete the following information):**
 - OS: MacOS Chrome
 - Version Version 90.0.4430.212 (Official Build) (x86_64)
- OpenSearch 1.0 RC1

**Comment by joshuali925** [comment]
This would be a feature request, currently the backend only supports returning a list of notebook titles

**Comment by stockholmux** [comment]
@joshuali925 The shorter path might be to clarify the label of the search box. I'm not worried about the ability to search the report contents but rather the confusion

**Comment by joshuali925** [comment]
Got it, will update search box placeholder to `Search notebook name` instead of `Search notebooks`

**Comment by joshuali925** [comment]
Close by #42, will reopen if there is a need to search by content
