### ISSUE TITLE
Use SNAPSHOT artifacts from maven for dependencies

### ISSUE THREAD

**Issue by dblock** [opensearch-project/dashboards-notebooks#98]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/45, use SNAPSHOT Maven dependencies from [aws.oss.sonatype.org](https://aws.oss.sonatype.org/content/repositories/snapshots). See https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#building-within-the-opensearch-build-system for details.

https://github.com/opensearch-project/dashboards-notebooks/blob/main/.github/workflows/opensearch-notebooks-test-and-build-workflow.yml#L23

**Comment by joshuali925** [comment]
notebooks repo is deprecated and won't have more releases (it's now part of trace-analytics repo). we'll archive this repo soon.

**Comment by dblock** [comment]
> notebooks repo is deprecated and won't have more releases (it's now part of trace-analytics repo). we'll archive this repo soon.

Thanks, remove it from https://github.com/opensearch-project/opensearch-build/blob/main/meta/.meta as well please.

**Comment by CEHENKLE** [comment]
Perhaps we want to update the description/readme?

**Comment by anirudha** [comment]
not released in 1.2

**Comment by joshuali925** [comment]
will send a pr to update readme
